// Builds decks/human-or-ai.json for the Human or AI game. Runs at build time with internet; the fair ships
// the static deck. Re-runnable: every stage caches under .deckwork/ (gitignored, never committed).
//
//   node scripts/build-deck.mjs                 run every stage that has no cache yet
//   node scripts/build-deck.mjs --humans        (re)select the human half from the Enron corpus
//   node scripts/build-deck.mjs --generate      (re)generate AI counterparts via OpenRouter
//   node scripts/build-deck.mjs --calibrate     (re)estimate difficulty with cheap judge models
//   node scripts/build-deck.mjs --tells         (re)draft tells with a small Claude model for hand editing
//   node scripts/build-deck.mjs --assemble      write the deck from the caches
//
// Human half: the CMU Enron corpus (1999-2002, provably pre-LLM). Only folders of mail the person sent
// themselves are used, bodies only, anonymised, era-neutral, sensitive topics skipped rather than redacted.
// AI half: one counterpart per human item matched on purpose, length, register and formatting, generated by a
// rotation of cheap models at varied temperature so no single voice gives the game away.

import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const work = path.join(root, '.deckwork')
mkdirSync(work, { recursive: true })
const args = new Set(process.argv.slice(2))
const stageFlags = ['--humans', '--generate', '--calibrate', '--tells', '--assemble']
const explicit = stageFlags.some((f) => args.has(f))
const want = (f) => (explicit ? args.has(f) : true)

const ARCHIVE_URL = 'https://www.cs.cmu.edu/~enron/enron_mail_20150507.tar.gz'
const ARCHIVE = process.env.ENRON_ARCHIVE ?? path.join(work, 'enron_mail_20150507.tar.gz')
const MAILDIR = path.join(work, 'maildir')
const TARGET_HUMANS = Number(process.env.DECK_HUMANS ?? 40)
const OUT = path.join(root, 'decks', 'human-or-ai.json')

// ------------------------------------------------------------------ env

function loadEnv() {
  const file = path.join(root, '.env')
  if (!existsSync(file)) return
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/)
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '')
  }
}
loadEnv()

const log = (...a) => console.log(...a)
const readJson = (p, fallback) => (existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : fallback)
const writeJson = (p, v) => writeFileSync(p, JSON.stringify(v, null, 2) + '\n')
const words = (t) => t.trim().split(/\s+/).filter(Boolean)
const sha = (t) => createHash('sha1').update(t).digest('hex').slice(0, 8)

// ------------------------------------------------------------------ stage 1: the corpus

function ensureCorpus() {
  if (existsSync(MAILDIR) && readdirSync(MAILDIR).length > 0) return
  if (!existsSync(ARCHIVE)) {
    log(`downloading ${ARCHIVE_URL} (about 420 MB)`)
    const r = spawnSync('curl', ['-L', '--progress-bar', '-o', ARCHIVE, ARCHIVE_URL], { stdio: 'inherit' })
    if (r.status !== 0) throw new Error('download failed')
  }
  log('extracting sent folders only (this takes a few minutes)')
  mkdirSync(work, { recursive: true })
  const r = spawnSync(
    'tar',
    ['-xzf', ARCHIVE, '-C', work, '--wildcards', '*/sent/*', '*/sent_items/*', '*/_sent_mail/*'],
    { stdio: 'inherit' },
  )
  if (r.status !== 0) throw new Error('extract failed')
}

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name)
    const st = statSync(p)
    if (st.isDirectory()) yield* walk(p)
    else yield p
  }
}

// ------------------------------------------------------------------ stage 2: cleaning

const FIRST_NAMES = new Set(
  `james john robert michael william david richard joseph thomas charles christopher daniel matthew anthony mark donald steven paul andrew joshua kenneth kevin brian george timothy ronald edward jason jeffrey ryan jacob gary nicholas eric jonathan stephen larry justin scott brandon benjamin samuel gregory frank alexander raymond patrick jack dennis jerry tyler aaron jose adam henry nathan douglas zachary peter kyle walter ethan jeremy harold keith christian roger noah gerald carl terry sean austin arthur lawrence jesse dylan bryan joe jordan billy bruce albert willie gabriel logan alan juan wayne roy ralph randy eugene vincent russell elijah louis bobby philip johnny mary patricia jennifer linda elizabeth barbara susan jessica sarah karen nancy lisa betty margaret sandra ashley kimberly emily donna michelle dorothy carol amanda melissa deborah stephanie rebecca sharon laura cynthia kathleen amy shirley angela helen anna brenda pamela nicole emma samantha katherine christine debra rachel catherine carolyn janet ruth maria heather diane virginia julie joyce victoria olivia kelly christina lauren joan evelyn judith megan cheryl andrea hannah martha jacqueline frances gloria ann teresa kathryn sara janice jean alice madison doris abigail julia judy grace denise amber marilyn beverly danielle theresa sophia marie diana brittany natalie isabella charlotte rose alexis kayla lori sally jeff mike tom bob bill dave dan chris steve jim rick greg kim sue liz tim ken ron phil jon vince chuck ed matt pat kate beth stan louise sherri sheila debbie kay lynn tana sara tracy jan vicki vince kevin kay mark jeff sally darrell phillip ben carol shirley randy fletcher rob larry drew jeffrey elizabeth sherry stacey michelle courtney amy jason chris kate cindy kathy suzanne mary rod marc leslie susan tori rhonda dan brent bert john greg sean keith mike shelley tammy lavorato hunter dana rosalee`
    .split(/\s+/),
)
const NEUTRAL = ['Alex', 'Sam', 'Jordan', 'Taylor', 'Morgan', 'Casey', 'Riley', 'Jamie', 'Drew', 'Robin', 'Avery', 'Quinn']

const SKIP_WORDS =
  /\b(enron|ees|ena|ect|eol|enrononline|dynegy|azurix|portland general|pge|ets|ebs|netco|ubs|el paso|calpine|reliant|duke|williams|sempra|nymex|ferc|pira|mwh?|mmbtu|megawatts?|noms?|nominations?|pipeline|gas daily|henry hub|curves?|hedge|swaps?|options?|traders?|trading|desk|books?|deals?|tickets?|invoices?|counterpart(?:y|ies)|schedul(?:e|ing)rs?|volumes?|prices?|burn|gen|balance sheet|compliant|sar|cash balance|intranet|extranet|pacer|modem|dial-?up|aol|msn|hotmail|yahoo|netscape|napster|palm|blackberry|pager|fax(?:es|ed)?|voicemail|voice mail|cell phone|cellphone|cell|dsl|cd-?rom|floppy|y2k|world trade|terror|bankrupt|chapter 11|sec|investigation|subpoena|lawsuit|attorney|lawyer|legal|litigation|deposition|testif\w*|fired|terminat\w*|layoffs?|laid off|severance|resign\w*|salary|salaries|bonus(?:es)?|raise|promotion|performance review|hr|human resources|harass\w*|discriminat\w*|pregnan\w*|baby|maternity|wedding|marri\w*|divorce\w*|husband|wife|girlfriend|boyfriend|dating|date night|love you|love ya|xoxo|kiss\w*|hugs?|honey|sweetie|sick|ill|illness|doctor|dr|hospital|surgery|cancer|died|death|funeral|passed away|pain|back|gym|diet|drunk|drinks?|drinking|hangover|bar|beer|wine|jail|police|arrest\w*|gun|ssn|social security|password|account (?:number|no)|credit card|routing|mortgage|loan|debt|rent|apartment|church|pray\w*|god|jesus|bible|birthday|xmas|christmas|thanksgiving|easter|hanukkah|halloween|super bowl|bowl|football|baseball|basketball|hockey|golf|pool|bet|betting|wager|astros|rockets|texans|cowboys|longhorns|aggies|steelers|titans|lsu|houston|texas|california|london|calgary|portland|omaha|new york|chicago|dallas|austin|denver|whistler|tacoma|india|mexico|vegas|allen center|smith street|west point)\b/i
// Things that a word-boundary regex cannot catch: money, percentages, maths, long numbers, dates.
const SKIP_SYMBOLS = /\$|£|€|\d\s?%|\d+\s*[x*\/]\s*\d+|\d{3,}|\b\d+\s?k\b|\b\d{1,2}(?:st|nd|rd|th)\b|9\/11/i
// Not for a public hall: swearing, interpersonal digs, health, politics.
const SKIP_TONE =
  /\b(fuck\w*|shit\w*|bullshit|ass\b|asses|half-assed|damn|hell\b|crap|bitch\w*|bastard|piss\w*|sucks?|screw\w*|idiot|stupid|moron|jerk|hate|mad at|upset|attitude|scares? me|not nice|annoy\w*|rude|nasty|gossip|dentist|dental|therapy|therapist|medic\w*|prescription|pills?|bush|gore|clinton|president|election|congress|senate|governor|crisis|war\b|iraq|afghanistan|israel|terror\w*|racis\w*|sexis\w*|gay|lesbian|religio\w*|muslim|christian|jewish)\b/i
const MONTHS = /\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|sept|oct|nov|dec)[a-z]*\.?\s+\d{1,2}\b|\b\d{1,2}\s+(?:jan|feb|mar|apr|may|jun|jul|aug|sep|sept|oct|nov|dec)[a-z]*\b/i
const FORMAT_SKIP = /https?:\/\/|www\.|@|\d{3}[-.)]\s?\d{3}[-.]\d{4}|\|\||\t|={3,}|-{5,}|_{4,}|\*{3,}|<[^>]+>|\[[^\]]+\]|\d{1,2}:\d{2}|\b(?:19|20)\d{2}\b|\d{1,2}\/\d{1,2}(?:\/\d{2,4})?/
const QUOTE_MARKERS = [
  /-{3,}\s*original message\s*-{3,}/i,
  /-{3,}\s*forwarded by/i,
  /-{3,}\s*forwarded message/i,
  /^\s*from:\s/im,
  /^\s*to:\s/im,
  /^\s*sent:\s/im,
  /^\s*subject:\s/im,
  /^\s*>/m,
  /^\s*cc:\s/im,
  /^\s*x-/im,
]
const SIGNOFF = /^(thanks|thank you|thx|thanx|regards|best|cheers|sincerely|later|talk soon|take care|ttyl|yours|best regards|kind regards|many thanks|ciao|bye|see ya|love)[\s,.!]*$/i

// Words that are also common English and must not be treated as names on their own.
const NAME_ALLOW = new Set(
  'will may bill mark june april grace hope pat rob rich frank art dawn faith joy sue ray guy jack jay lee gene bob don tim pat max sam chase hunter cliff rose lily jade brooke ivy amber ruby holly summer autumn crystal dean earl grant hardy herb hobby jerry jimmy kay king lane lynn marsh miles page park price ross royal sandy sky stone tiger west wood young wade dale glen bing'.split(' '),
)

// English words, so an unknown lowercase token is probably a name, a place, jargon or a typo.
let DICT = null
function dictionary() {
  if (DICT) return DICT
  DICT = new Set()
  for (const f of ['/usr/share/dict/words', '/usr/share/dict/cracklib-small']) {
    if (!existsSync(f)) continue
    for (const w of readFileSync(f, 'utf8').split('\n')) if (w) DICT.add(w.toLowerCase())
  }
  for (const w of 'ok okay thx thanx pls plz fyi asap btw tba tbd lol hey hi ya yep yup nope gonna wanna gotta kinda sorta dunno cuz coz thru tho nite tonite pm am re fwd cc bcc etc vs eg ie ur u r im ive dont cant wont didnt doesnt isnt wasnt arent werent havent hasnt hadnt couldnt wouldnt shouldnt youre theyre weve youve theyve lets thats whats hes shes ill youll theyll itll id youd hed shed wed'.split(' ')) DICT.add(w)
  return DICT
}

// First and last names seen in the corpus headers; built while scanning.
const NAME_TOKENS = new Set()
function harvestNames(headers) {
  for (const line of headers.match(/^X-(?:From|To|cc|bcc):.*$/gim) ?? []) {
    for (const tok of line.replace(/^X-[A-Za-z]+:/, '').replace(/<[^>]*>|@\S+|\/[A-Z=\w]+/g, ' ').split(/[\s,;"'()]+/)) {
      const t = tok.toLowerCase().replace(/[^a-z-]/g, '')
      if (t.length >= 3 && !NAME_ALLOW.has(t)) NAME_TOKENS.add(t)
    }
  }
}

function parseMessage(raw) {
  const split = raw.indexOf('\n\n')
  if (split < 0) return null
  const headers = raw.slice(0, split)
  let body = raw.slice(split + 2)
  harvestNames(headers)
  const from = /^X-From:\s*(.*)$/im.exec(headers)?.[1] ?? ''
  const subject = /^Subject:\s*(.*)$/im.exec(headers)?.[1] ?? ''
  // Cut at the first quoted or forwarded block; keep what the author typed.
  let cut = body.length
  for (const re of QUOTE_MARKERS) {
    const m = re.exec(body)
    if (m && m.index < cut) cut = m.index
  }
  body = body.slice(0, cut)
  // Quoted-printable leftovers and hard wraps.
  body = body.replace(/=20/g, ' ').replace(/=09/g, ' ').replace(/=\r?\n/g, '').replace(/\r/g, '')
  body = body.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim()
  // Drop a trailing sign-off and the name lines after it.
  const lines = body.split('\n')
  while (lines.length) {
    const last = lines[lines.length - 1].trim()
    if (
      !last ||
      SIGNOFF.test(last.replace(/,$/, '')) ||
      /^[A-Z][a-z]+( [A-Z]\.?)?( [A-Z][a-z]+)?$/.test(last) ||
      /^[A-Za-z]{1,4}[.]?$/.test(last) ||
      /^-+$/.test(last)
    )
      lines.pop()
    else break
  }
  body = lines.join('\n').trim()
  return { from, subject, body }
}

function anonymise(text, authorFirst) {
  const map = new Map()
  let next = 0
  const sub = (name) => {
    const key = name.toLowerCase()
    if (!map.has(key)) map.set(key, NEUTRAL[next++ % NEUTRAL.length])
    return map.get(key)
  }
  // "Firstname Lastname" pairs and lone first names from the list; the author's own name too.
  let out = text.replace(/\b([A-Z][a-z]{2,})\s+([A-Z][a-z]+(?:-[A-Z][a-z]+)?)\b/g, (m, a, _b) => (FIRST_NAMES.has(a.toLowerCase()) ? sub(a) : m))
  out = out.replace(/\b([A-Z][a-z]{2,})\b/g, (m, a) => (FIRST_NAMES.has(a.toLowerCase()) ? sub(a) : m))
  if (authorFirst && authorFirst.length > 2) out = out.replace(new RegExp(`\\b${authorFirst}\\b`, 'gi'), sub(authorFirst))
  // Anything still looking like a surname after a substituted name is a leak: "Alex Lavorato".
  if (/\b(?:Alex|Sam|Jordan|Taylor|Morgan|Casey|Riley|Jamie|Drew|Robin|Avery|Quinn) [A-Z][a-z]+\b/.test(out)) return null
  return out
}

function registerOf(text) {
  const w = words(text)
  const lower = text === text.toLowerCase()
  const greeting = /^(hi|hello|hey|dear|good morning|good afternoon)\b/i.test(text)
  const exclaim = (text.match(/!/g) ?? []).length
  const question = /\?/.test(text)
  const typos = /\b(teh|recieve|seperate|definately|alot|thier|occured|untill)\b/i.test(text) || /\s[,.]/.test(text)
  const caps = w.filter((x) => /^[A-Z]{2,}$/.test(x)).length
  return { words: w.length, lower, greeting, exclaim, question, typos, caps, lines: text.split('\n').length }
}

function bodyOk(text, subject) {
  const n = words(text).length
  if (n < 15 || n > 60) return 'length'
  if (FORMAT_SKIP.test(text) || FORMAT_SKIP.test(subject)) return 'format'
  if (SKIP_SYMBOLS.test(text) || MONTHS.test(text)) return 'numbers'
  if (SKIP_WORDS.test(text) || SKIP_WORDS.test(subject)) return 'topic'
  if (SKIP_TONE.test(text) || SKIP_TONE.test(subject)) return 'tone'
  // Acronyms are organisations, systems or jargon nine times out of ten.
  const acronyms = (text.match(/\b[A-Z]{2,}\b/g) ?? []).filter((a) => !new Set(['OK', 'PS', 'FYI', 'ASAP', 'AM', 'PM', 'TV', 'PC', 'US', 'UK', 'IT', 'HR', 'CEO', 'BTW', 'RSVP', 'ID']).has(a))
  if (acronyms.length) return 'acronym'
  if (text.split('\n').filter((l) => l.trim() && words(l).length < 4).length > 2) return 'mangled'
  if (/^\s*\d+[.)]/m.test(text)) return 'list'
  const dict = dictionary()
  let unknown = 0
  for (const raw of text.split(/[^A-Za-z'-]+/)) {
    const t = raw.toLowerCase().replace(/^'+|'+$/g, '')
    if (t.length < 3) continue
    if (NAME_TOKENS.has(t) && !NAME_ALLOW.has(t) && !dict.has(t)) return `name:${t}`
    if (!dict.has(t) && !dict.has(t.replace(/'s$/, '')) && !/^(?:\w)\1*$/.test(t)) {
      if (NAME_TOKENS.has(t)) return `name:${t}`
      unknown++
      if (unknown > 1) return `unknown:${t}`
    }
  }
  return null
}

function selectHumans() {
  const cache = path.join(work, 'humans.json')
  ensureCorpus()
  // Pass one: parse everything (harvesting names from headers) and keep bodies that look promising.
  const parsed = []
  let scanned = 0
  for (const file of walk(MAILDIR)) {
    scanned++
    let raw
    try {
      raw = readFileSync(file, 'latin1')
    } catch {
      continue
    }
    const msg = parseMessage(raw)
    if (!msg || !msg.body) continue
    const n = words(msg.body).length
    if (n < 15 || n > 60) continue
    parsed.push(msg)
  }
  log(`scanned ${scanned} messages, ${parsed.length} bodies of 15-60 words, ${NAME_TOKENS.size} name tokens harvested`)
  // Pass two: strict filters now that the name list is complete.
  const seen = new Set()
  const candidates = []
  const reasons = {}
  for (const msg of parsed) {
    const why = bodyOk(msg.body, msg.subject)
    if (why) {
      const k = why.split(':')[0]
      reasons[k] = (reasons[k] ?? 0) + 1
      continue
    }
    const authorFirst = (msg.from.match(/,\s*([A-Za-z]+)/)?.[1] ?? msg.from.split(/\s+/)[0] ?? '').replace(/[^A-Za-z]/g, '')
    const text = anonymise(msg.body, authorFirst)
    if (!text) continue
    // Any remaining capitalised word that is neither a sentence start, a weekday, nor a neutral name: skip.
    const suspects = text.match(/(?<![.!?\n]\s|^)\b[A-Z][a-z]{2,}\b/g) ?? []
    const allowed = new Set([...NEUTRAL, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Thanks', 'Please', 'Also', 'Just', 'Let', 'The', 'This', 'That', 'Yes', 'Okay', 'Sorry', 'Great', 'Good', 'Thank', 'Hope', 'Would', 'Could', 'Can', 'Will', 'Should', 'What', 'When', 'Where', 'Who', 'How', 'Why', 'Any', 'All', 'One', 'Two', 'Three', 'Since', 'After', 'Before', 'Then', 'Here', 'There', 'Not', 'Are', 'Was', 'Were', 'Have', 'Has', 'Had', 'And', 'But', 'For', 'With', 'From', 'Your', 'You', 'Our', 'Its', 'His', 'Her', 'Him', 'She', 'They', 'Them', 'Their', 'Some', 'Each', 'Every', 'Most', 'Much', 'Many', 'Very', 'Well', 'Still', 'Sure', 'Maybe', 'Perhaps', 'Probably', 'Anyway', 'Again', 'Unfortunately', 'Hopefully', 'Actually', 'Basically', 'Apparently', 'Obviously', 'Finally', 'First', 'Second', 'Last', 'Next', 'Today', 'Tomorrow', 'Yesterday', 'Tonight', 'Morning', 'Afternoon', 'Evening', 'Week', 'Month', 'Year', 'Meeting', 'Call', 'Note', 'Fyi', 'Hi', 'Hello', 'Hey', 'Dear', 'Cheers', 'Regards', 'Best', 'Ok', 'Yeah', 'Also', 'However', 'Otherwise', 'Thursday'])
    if (suspects.some((w) => !allowed.has(w))) {
      reasons.capitalised = (reasons.capitalised ?? 0) + 1
      continue
    }
    const key = text.toLowerCase().replace(/[^a-z]/g, '').slice(0, 80)
    if (seen.has(key)) continue
    seen.add(key)
    candidates.push({ text, reg: registerOf(text), subject: msg.subject })
  }
  log(`${candidates.length} clean candidates; rejected: ${Object.entries(reasons).map(([k, v]) => `${k} ${v}`).join(', ')}`)
  // Spread across lengths and registers, deterministic per run.
  const rand = mulberry32(20260916)
  const buckets = { short: [], mid: [], long: [] }
  for (const c of candidates) (c.reg.words <= 25 ? buckets.short : c.reg.words <= 40 ? buckets.mid : buckets.long).push(c)
  const pick = []
  const per = Math.ceil(TARGET_HUMANS / 3)
  for (const b of Object.values(buckets)) {
    const shuffled = shuffle(b, rand)
    const groups = [
      shuffled.filter((c) => c.reg.lower),
      shuffled.filter((c) => c.reg.question),
      shuffled.filter((c) => c.reg.greeting),
      shuffled.filter((c) => !c.reg.greeting && !c.reg.lower),
    ]
    const chosen = new Set()
    let gi = 0
    while (chosen.size < per && groups.some((g) => g.length)) {
      const g = groups[gi % groups.length]
      gi++
      const c = g.shift()
      if (c && !chosen.has(c)) chosen.add(c)
    }
    pick.push(...chosen)
  }
  const humans = pick.slice(0, TARGET_HUMANS).map((c) => ({
    id: `h-${sha(c.text)}`,
    text: c.text,
    source: 'human',
    register: c.reg,
  }))
  writeJson(cache, humans)
  log(`selected ${humans.length} human items -> ${cache}`)
  return humans
}

function mulberry32(seed) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
function shuffle(items, rand) {
  const out = [...items]
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

// ------------------------------------------------------------------ OpenRouter

let spent = 0
async function chat(model, messages, { temperature = 0.9, max_tokens = 400 } = {}) {
  const key = process.env.OPENROUTER_API_KEY
  if (!key) throw new Error('OPENROUTER_API_KEY missing (put it in .env)')
  for (let attempt = 0; attempt < 4; attempt++) {
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${key}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://github.com/stallgamehub',
        'X-Title': 'stall game hub deck builder',
      },
      body: JSON.stringify({ model, messages, temperature, max_tokens, usage: { include: true } }),
    })
    if (res.status === 429 || res.status >= 500) {
      await new Promise((r) => setTimeout(r, 1500 * (attempt + 1)))
      continue
    }
    const json = await res.json()
    if (json.error) throw new Error(`${model}: ${json.error.message ?? JSON.stringify(json.error)}`)
    spent += Number(json.usage?.cost ?? 0)
    return json.choices?.[0]?.message?.content ?? ''
  }
  throw new Error(`${model}: gave up after retries`)
}

async function availableModels(preferred) {
  const key = process.env.OPENROUTER_API_KEY
  const res = await fetch('https://openrouter.ai/api/v1/models', { headers: { Authorization: `Bearer ${key}` } })
  const json = await res.json()
  const ids = new Set((json.data ?? []).map((m) => m.id))
  const found = preferred.filter((id) => ids.has(id))
  if (found.length === 0) throw new Error(`none of the preferred models exist: ${preferred.join(', ')}`)
  return found
}

// Non-thinking models only: reasoning models spend the small token budget on hidden thoughts and return nothing.
const GENERATORS = [
  'deepseek/deepseek-v4-flash-0731',
  'google/gemini-2.5-flash-lite',
  'openai/gpt-4.1-nano',
  'mistralai/mistral-small-3.2-24b-instruct',
  'meta-llama/llama-3.3-70b-instruct',
  'deepseek/deepseek-chat-v3.1',
]
const JUDGES = ['deepseek/deepseek-v4.1-flash', 'google/gemini-2.5-flash-lite', 'openai/gpt-4.1-nano', 'qwen/qwen3.7-flash', 'z-ai/glm-5.3-flash']
const TELL_MODEL = ['anthropic/claude-haiku-4.5', 'anthropic/claude-3-haiku']

const STYLES = [
  'all lowercase, no greeting, terse, one small typo',
  'friendly and slightly rushed, a greeting, no sign-off',
  'plain and neutral, short sentences, no greeting',
  'a little over-formal, full sentences, polite close',
  'chatty, at most one exclamation mark, a fragment or two',
  'clipped phrasing, abbreviations like pls and thx, no greeting',
  'apologetic tone, one run-on sentence, no sign-off',
  'brisk manager voice, an instruction and a deadline, no pleasantries',
  'trailing off with an ellipsis somewhere, lowercase, no greeting',
  'mildly annoyed but polite, two sentences, no greeting',
]

// Phrases that give a model away on sight. Any of these and the draft is thrown out.
const BANNED = /\b(just wanted to|hope (?:you're|you are|this finds you)|i hope you|looking forward to|thanks for understanding|thank you for your understanding|let me know if you (?:have any|need anything)|don't hesitate|feel free|circle back|align|touch base|reach out|going forward|at your earliest convenience|kindly|as per|please find|wanted to check in|checking in|quick (?:update|question|rundown)|heads[- ]up|happy to|excited to|thrilled|awesome|fantastic|wonderful|appreciate your|your (?:hard work|dedication|patience|input is)|it truly|truly|solid work|great work|absolutely|totally|definitely|super\b|bunch|hop on|game plan|bandwidth|deep dive|leverage|streamline|robust|delve|navigate|landscape|crucial|ensure|utilize|facilitate|additionally|furthermore|moreover|in conclusion|to summarize)\b/i

/** Straight quotes, plain dashes: the typography a 2001 email client produced. */
function normalise(text) {
  return text
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/\u2026/g, '...')
    .replace(/\s*[\u2014\u2013]\s*/g, (m) => (m.trim() ? ', ' : ' - '))
    .replace(/[\u00a0]/g, ' ')
    .replace(/\*\*/g, '')
    .replace(/[ \t]+\n/g, '\n')
    .trim()
}

/** Any capitalised name outside the neutral pool becomes one from the pool. */
function poolNames(text) {
  const known = new Set(NEUTRAL)
  let k = 0
  return text.replace(/\b([A-Z][a-z]{2,})\b(?=[,!.\s]|$)/g, (m, w, off) => {
    if (known.has(w)) return w
    const atStart = off === 0 || /[.!?]\s*$/.test(text.slice(0, off))
    if (atStart || !FIRST_NAMES.has(w.toLowerCase())) return m
    return NEUTRAL[k++ % NEUTRAL.length]
  })
}

function shapeOf(text, reg) {
  const bits = []
  bits.push(reg.lower ? 'entirely lowercase' : 'normal capitalisation')
  bits.push(reg.greeting ? 'opens with a greeting' : 'no greeting')
  bits.push(/[!]/.test(text) ? `${(text.match(/!/g) ?? []).length} exclamation mark(s)` : 'no exclamation marks')
  bits.push(/\.\.\./.test(text) ? 'uses an ellipsis' : 'no ellipsis')
  bits.push(/\?/.test(text) ? 'asks a question' : 'no question')
  bits.push(`${(text.match(/[.!?](\s|$)/g) ?? []).length} sentences`)
  bits.push(reg.lines > 2 ? 'two short paragraphs' : 'one paragraph')
  return bits.join(', ')
}

async function generateAi(humans) {
  const cache = path.join(work, 'ai.json')
  const existing = readJson(cache, {})
  const models = await availableModels(GENERATORS)
  log(`generators: ${models.join(', ')}`)
  const rand = mulberry32(7)
  let i = 0
  for (const h of humans) {
    if (existing[h.id]?.text) continue
    const n = h.register.words
    const style = STYLES[Math.floor(rand() * STYLES.length)]
    const temperature = 0.8 + rand() * 0.5
    const brief = await chat(
      models[i % models.length],
      [
        {
          role: 'system',
          content: 'You describe short workplace emails. Reply with one line: the purpose of the message, no names, no quoting, no judgement of quality.',
        },
        { role: 'user', content: h.text },
      ],
      { temperature: 0.3, max_tokens: 80 },
    )
    const prompt = `Write the body of a short internal email with this purpose: ${brief.trim()}
Shape to match: ${shapeOf(h.text, h.register)}. Length: ${n} words, give or take 2.
Voice: ${style}. This is a real person typing quickly to a colleague they know. Sound plain and specific, not polished. Do not be helpful or warm. No pleasantries, no "hope you are well", no "let me know if", no "looking forward", no "just wanted to". Straight quotes, no dashes. Use first names from this list only if you need one: Alex, Sam, Jordan, Taylor, Morgan, Casey. No subject line, no company names, no dates, no prices, no phone numbers, no links. Output only the email body.`
    let best = null
    for (let attempt = 0; attempt < 5; attempt++) {
      const m = models[(i + attempt) % models.length]
      let out = await chat(m, [{ role: 'user', content: prompt }], { temperature, max_tokens: 300 })
      out = poolNames(normalise(out.replace(/^["“]|["”]$/g, '').replace(/^subject:.*\n/i, '').trim()))
      const wn = words(out).length
      if (wn === 0) continue
      const banned = BANNED.test(out)
      const score = Math.abs(wn - n) + (banned ? 20 : 0) + (/\bAI\b|language model|assistant/i.test(out) ? 100 : 0) + (FORMAT_SKIP.test(out) ? 50 : 0)
      if (!best || score < best.score) best = { out, score, wn, model: m }
      if (best.score <= 2) break
    }
    i++
    if (!best || best.score >= 20 || best.wn < 15 || best.wn > 60) {
      log(`  ${h.id}: no clean match (${best?.wn ?? 0} words, score ${best?.score}), skipping`)
      continue
    }
    existing[h.id] = { id: `a-${sha(best.out)}`, text: best.out, source: 'ai', model: best.model, style, temperature: Math.round(temperature * 100) / 100, pairedWith: h.id }
    writeJson(cache, existing)
    log(`  ${h.id} -> ${existing[h.id].id} via ${best.model} (${best.wn} words) $${spent.toFixed(3)} so far`)
  }
  return existing
}

// ------------------------------------------------------------------ calibration: cheap judges guess, difficulty follows

async function calibrate(humans, ai) {
  // Pairwise: each judge sees the human item and its counterpart and must name the machine. Single-item
  // judgements are useless here (cheap models call everything human); pairs give a real signal.
  const cache = path.join(work, 'votes.json')
  const votes = readJson(cache, {})
  const judges = await availableModels(JUDGES)
  log(`judges: ${judges.join(', ')}`)
  const rand = mulberry32(99)
  for (const h of humans) {
    const a = ai[h.id]
    if (!a) continue
    votes[h.id] ||= {}
    for (const j of judges) {
      if (votes[h.id][j]) continue
      const aiFirst = rand() < 0.5
      const [first, second] = aiFirst ? [a.text, h.text] : [h.text, a.text]
      const out = await chat(
        j,
        [
          {
            role: 'system',
            content: 'Two short emails. Exactly one was generated by a language model, the other was typed by a person. Answer with exactly one letter, A or B, for the machine-written one.',
          },
          { role: 'user', content: `A:\n${first}\n\nB:\n${second}` },
        ],
        { temperature: 0, max_tokens: 3 },
      )
      const pick = /\bB\b/i.test(out) ? 'B' : 'A'
      votes[h.id][j] = (pick === 'A') === aiFirst ? 'right' : 'wrong'
    }
    writeJson(cache, votes)
  }
  log(`calibrated ${humans.length} pairs, $${spent.toFixed(3)} spent`)
  return votes
}

function difficultyFrom(pairId, votes) {
  const v = Object.values(votes[pairId] ?? {})
  if (v.length === 0) return 2
  const right = v.filter((x) => x === 'right').length / v.length
  return right >= 0.99 ? 1 : right >= 0.6 ? 2 : 3
}

// ------------------------------------------------------------------ tells: drafted by a small Claude, edited by hand

async function draftTells(items) {
  const cache = path.join(work, 'tells.json')
  const tells = readJson(cache, {})
  const [model] = await availableModels(TELL_MODEL)
  for (const it of items) {
    if (tells[it.id]) continue
    const out = await chat(
      model,
      [
        {
          role: 'system',
          content:
            'You write one-sentence explanations for a game where players guess if a short email is human-written or AI-generated. Given the text and the true answer, name the single most convincing tell in under 20 words, concrete and specific to this text, in plain British English, no hedging, no quotes around the whole sentence.',
        },
        { role: 'user', content: `Answer: ${it.source === 'ai' ? 'AI-generated' : 'written by a person in 2001'}\n\n${it.text}` },
      ],
      { temperature: 0.4, max_tokens: 60 },
    )
    tells[it.id] = out.trim().replace(/^["“]|["”]$/g, '')
    writeJson(cache, tells)
  }
  log(`drafted tells, $${spent.toFixed(3)} spent`)
  return tells
}

// ------------------------------------------------------------------ assemble

function assemble(humans, ai, votes, tells) {
  const prev = readJson(OUT, { items: [] })
  const prevById = new Map(prev.items.map((i) => [i.id, i]))
  const items = []
  for (const h of humans) {
    const a = ai[h.id]
    if (!a) continue
    for (const it of [h, a]) {
      const n = words(it.text).length
      const old = prevById.get(it.id)
      items.push({
        id: it.id,
        text: it.text,
        source: it.source,
        // Hand-edited tells in the existing deck win over fresh drafts.
        tell: old?.tell || tells[it.id] || '',
        durationMs: old?.durationMs ?? Math.round(Math.min(15, Math.max(6, 3 + n * 0.25)) * 1000),
        difficulty: old?.difficulty ?? difficultyFrom(h.id, votes),
      })
    }
  }
  items.sort((x, y) => x.difficulty - y.difficulty || x.id.localeCompare(y.id))
  writeJson(OUT, { generatedAt: new Date().toISOString(), items })
  const humansN = items.filter((i) => i.source === 'human').length
  log(`deck: ${items.length} items (${humansN} human, ${items.length - humansN} ai) -> ${OUT}`)
  const d = [1, 2, 3].map((k) => items.filter((i) => i.difficulty === k).length)
  log(`difficulty 1/2/3: ${d.join('/')}, total spend $${spent.toFixed(3)}`)
}

// ------------------------------------------------------------------ main

const humansCache = path.join(work, 'humans.json')
let humans = readJson(humansCache, null)
if (want('--humans') && (explicit || !humans)) humans = selectHumans()
if (!humans) throw new Error('no humans selected; run with --humans')

let ai = readJson(path.join(work, 'ai.json'), {})
if (want('--generate') && (explicit || Object.keys(ai).length < humans.length)) ai = await generateAi(humans)

const paired = humans.filter((h) => ai[h.id])
const all = [...paired, ...paired.map((h) => ai[h.id])]
let votes = readJson(path.join(work, 'votes.json'), {})
if (want('--calibrate') && (explicit || Object.keys(votes).length < paired.length)) votes = await calibrate(paired, ai)

let tells = readJson(path.join(work, 'tells.json'), {})
if (want('--tells') && (explicit || Object.keys(tells).length < all.length)) tells = await draftTells(all)

if (want('--assemble')) assemble(paired, ai, votes, tells)
