// Copies the pixel icons the UI uses out of @hackernoon/pixel-icon-library (MIT) into a generated module,
// so they are inlined as SVG paths and can be coloured with currentColor. Re-run after adding a name below.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const src = path.join(root, 'node_modules', '@hackernoon', 'pixel-icon-library', 'icons', 'SVG')
const WANTED = {
  pencil: 'solid/pencil-solid.svg',
  check: 'solid/check-solid.svg',
  play: 'solid/play-solid.svg',
  user: 'solid/user-solid.svg',
  users: 'solid/users-solid.svg',
  clock: 'solid/clock-solid.svg',
  trophy: 'solid/trophy-solid.svg',
  volume: 'solid/sound-on-solid.svg',
  volumeMute: 'solid/sound-mute-solid.svg',
  bolt: 'solid/bolt-solid.svg',
  info: 'solid/info-circle-solid.svg',
  times: 'solid/times-solid.svg',
  hourglass: 'solid/clock-solid.svg',
  flag: 'solid/flag-checkered-solid.svg',
  crown: 'solid/crown-solid.svg',
  question: 'solid/question-circle-solid.svg',
}
const out = {}
for (const [name, rel] of Object.entries(WANTED)) {
  const file = path.join(src, rel)
  if (!existsSync(file)) {
    console.error(`missing icon ${rel}`)
    process.exit(1)
  }
  const svg = readFileSync(file, 'utf8')
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 24 24'
  out[name] = { viewBox, inner }
}
const ts = `// Generated by scripts/vendor-icons.mjs from @hackernoon/pixel-icon-library (MIT). Do not edit.
export const PIXEL_ICONS = ${JSON.stringify(out, null, 2)} as const
export type PixelIconName = keyof typeof PIXEL_ICONS
`
writeFileSync(path.join(root, 'components', 'shared', 'pixelIcons.ts'), ts)
console.log(`wrote ${Object.keys(out).length} icons`)
